events.go

Need to send team with this since it's not part of user, and won't be unless the user accepts this invite we're sending out.

We'll need team name too.

---

scanner.go
scanner/external_coverage.go
scanner/external_scan.go
scanner/external_vulnerabilities.go
scanner/scanner.go
scanner_test.go

Add scanner

---

analysis/analysis.go

Adding ID field to go alongside analysis_id field

Adding ID field

---

events/delivery_events.go
events/delivery_events_test.go
events/events.go

adding event for delivery

---

dependencies.go

https://ionchannel.atlassian.net/browse/CS-1980

Fixes error message in GetLatestVersionForDependency, fixes CS-1980

---

client.go

For https://ionchannel.atlassian.net/browse/CS-1984

passing response body through with error on bad error code in client

---

digests/digests.go
digests/ecosystems.go
digests/ecosystems_test.go

* changes dominant languages to be just languages digest
* changes tile to show single language name if one is present or a number if many are present

Languages Digest

---

client.go
client_test.go
requests/requests.go
requests/requests_test.go

May need better comments to differentiate use of helper/wrapper methods.

Add requests package

---

portfolios.go
portfolios/portfolios.go
portfolios_test.go

adds GetRawVulnerabilityMetrics and GetPortfolioStatusSummary

Add get raw vulnerability metrics get portfolio status summary

---

scanner/analysis_status.go

a github search for this constant in the ion-channel org only returned these.

changes the constant to queued.

---

digests/vulnerabilities.go
digests/vulnerabilities_test.go

Add test for desired behavior.

---

reports/analysis.go
scanner.go
scanner_test.go

These missed the boat getting upstreamed to here.

Reintroduce analysis status field usage.

---

digests/buildsystems.go
digests/buildsystems_test.go

also adds unit tests for container dependency digests

fixes issue using container image count instead of dependency count

---

Gopkg.lock
digests/dependencies.go
digests/dependencies_test.go
scans/results.go
vendor/github.com/hashicorp/go-version/LICENSE
vendor/github.com/hashicorp/go-version/README.md
vendor/github.com/hashicorp/go-version/constraint.go
vendor/github.com/hashicorp/go-version/go.mod
vendor/github.com/hashicorp/go-version/version.go
vendor/github.com/hashicorp/go-version/version_collection.go

- update tests
- update test for dependency outdated counts
- fix for outdated top level deps
- update Gopkg.toml, update vendored code with dep ensure

[ION-499, ION-497] updated outdated deps to track major minor version behind

---

digests/community.go
digests/community_test.go
digests/digests.go
scans/results.go

Revert "[ION-575] update community results to include committed at time"

---

spdx/spdx.go

Get the default branch on checkout.

Set SPDX import default branch names to HEAD.

---

.gitignore
analyses/analyses.go

Just adds extra fields to the ExportData struct

[ION-722] [ION-685] [ION-707] Add some extra fields to project export

---

community.go
community_test.go

- Refactor the in common handler
- Lower case options
- lower only comparands for now
- Unmarshal the counts
- Revert option lower

refactor in common

---

projects/projects.go
projects/projects_test.go

Allows filtering DB queries on multiple IDs, rather than only one ID

Allow filtering on multiple IDs

---

analyses/analyses.go
analyses/analyses_test.go
reports/analysis.go

Refactors Analysis and Summary structs to make it more clear what the difference is between them.

Clean up Analysis and Summary structs

---

spdx/spdx.go

Spec says this is a valid value for this field

Support NONE for SPDX PackageDownloadLocation

---

go.mod
go.sum
spdx/spdx.go
spdx/spdx_test.go
vendor/modules.txt

Draft while I use this commit in our service and verify it works as expected. 😄

Convert spdx noassertion version to blank

---

organizations.go
organizations/organizations.go
organizations/organizations_test.go
organizations_test.go
rulesets/applied_rulesets.go
teams/teams.go
teams/teams_test.go
users.go
users/users.go
users/users_test.go

Adds organizations.
Also adds the UpdateUserPreferences and UpdateOwnUserPreferences methods for setting email notification preferences.

[ION-843] Add organizations, UpdateUserPreferences method

---

client.go

Adds a field for a Session in the IonClient struct.
Adds methods for enabling/disabling the automatic renewal of the Session every 13 minutes.
The Session is not automatically used for any requests, but it is available for use. For example:
```
token := myClient.Session().BearerToken
myClient.GetSelf(token)
```

Add Session auto-renewal method to IonClient

---

client.go
rulesets.go
rulesets/rulesets.go

Add GetDefaultRulesets method

---

projects/sboms.go
sboms.go

Add SBOM endpoints

---

projects/sboms.go

Refactors SBOMEntry to support upcoming API changes

[ION-1196] Refactor SBOMEntry struct

---

cyclonedx/cyclonedx.go
spdx/spdx.go

Grabs some additional information from CycloneDX and SPDX SBOMs when we ingest them.

[ION-1217] Get CPE and PURL when parsing SBOMs

---

projects/sboms.go

Adds counts for unresolved, partially resolved, and resolved entries.

[ION-1259] Add various counts to SBOMs

---

organizations/organizations.go
organizations/organizations_test.go
projects/sbom_entry_search_results.go

- Adds `IsUserInput` bool to SBOMSearchResultGeneric struct
- Adds `Members` list to Organization struct

[ION-1291] [ION-1407] Add fields to Organization and SBOM Search Result structs

---

projects/sboms.go

Makes it easier to work with on the front-end

Fix capitalization, rename some JSON properties

---

go.mod
go.sum
vendor/github.com/spdx/tools-golang/spdxlib/documents.go
vendor/github.com/spdx/tools-golang/spdxlib/element_ids.go
vendor/github.com/spdx/tools-golang/spdxlib/relationships.go
vendor/modules.txt

We can stop using our fork now.

[DEV-341] Update spdx/tool-golang dependency

---

projects/software_lists.go

[DEV-1243] Software -> Technology in risk scopes

---

community/community.go
risk/risk.go

- Break out metrics into new struct for community
- Fix type for mtty
- More floating up

community metrics

---

community/community.go

Removes eol from metric obj (metric no longer in use)

remove eol from metric obj

---

projects/software_lists.go

Helps account for scopes we are going to add in the future, and accounts for missing scores

Change risk scopes to map

---

dependencies/dependencies.go
products/products.go

- Add the new fields for search response
- Adding matches to dependencies and products

new fields

---

generated.go
models_gen.go
organizations.go
organizations/organizations.go
schema.graphqls
sessions.go
users.go
users/users.go

- Revert structs back to the packages
- Adding joined at
- Adding new fields for roles and members
- Joined at is optional
- more reverting
- Correct expected arguments
- Email for members

new role fields

---

software_lists.go

Required for https://github.com/ion-channel/graphql-server/pull/34

GetSoftwareLists returns a SoftwareList instead of SoftwareInventory
