ion-channel/ionic

events/events.go
events/events_test.go
rules/rules.go
rulesets.go
rulesets/rulesets.go
sessions.go
users.go
users/users.go
users_test.go
vulnerabilities.go
vulnerabilities/vulnerabilities.go

Splits the project into packages based on the structs.
The ionic client is the primary package, and contains all of the ion clients methods.  Each of our other objects gets its own package to contain methods relevant to those objects.

Splitting into package

---

rules/rules.go

i'm not sure if this breaks anything else downstream. i checked in the ui and removed any references, but didn't see anything that would actually break:
https://github.com/ion-channel/ion-ui/pull/887

remove unused Rule struct members

---

reports/analysis_test.go
scans/results.go
scans/results_test.go
scans/scans.go

* Changes scan translate method to dereference pointers for data and match parity with our custom unmarshaller
* Updates New scan constructor to favor translated results over untranslated results like everywhere else

Consistency Wins

---

projects/projects.go
projects/projects_test.go

This is a service's purview, especially when we add connectivity checking. No need to add the AWS SDK to this project if we can avoid it. 👍

Remove ssh key checking

---

reports/analysis.go

It's possible to have a scan status here but not an analysis, this allows us to use fallback created_at and updated_at timestamps for the response.

Fall back to scan status dates if analysis isn't present.

---

digests/dependencies.go

See here on ingest https://github.com/ion-channel/doozers/blob/76185caf20c3dcc5ddc91330cc17affced501f42/lib/doozers/dependency.rb#L87
doozer calculates to check if specified verison is 0, we should also do an check for empty requirement.

add an empty string check for outdated dependencies

---

projects/projects.go

Makes the audit trail of who changed what, when, on rulesets easier to follow/display.

Update ruleset history to include the changed from and changed to items.

---

responses/responses.go
responses/responses_test.go

- Updates `responses/responses.go`, updates `Meta` struct to safely use `omitempty` with `time.Time` type. 
For context: time.Time can't be used with `omitempty` (as it will come across as year 1 of `"0001-01-01T00:00:00Z"`) when marshall/unmarshalling.
See example of this [here](https://play.golang.org/p/L5cXqrYoq7M)

update response Meta to include correctly marshalled timestamp

---

scanner/analysis_status.go
scanner/analysis_status_test.go

Updates `analysis_status.go`, adding property to track unreachable error in the `AnalysisStatus` struct.

update analysisStatus to track project unreachable status

---

scanner/analysis_status.go

- Updates `analysis_status.go`, updates `AnalysisStatus` struct adding back in a field for analysis event source that is relied on in kermit but was not being populated.

[ION-501] add analysis event source to analysis status struct

---

Gopkg.lock
digests/dependencies.go
digests/dependencies_test.go
scans/results.go
vendor/github.com/hashicorp/go-version/LICENSE
vendor/github.com/hashicorp/go-version/README.md
vendor/github.com/hashicorp/go-version/constraint.go
vendor/github.com/hashicorp/go-version/go.mod
vendor/github.com/hashicorp/go-version/version.go
vendor/github.com/hashicorp/go-version/version_collection.go

- Updates `digests/dependencies.go`, adding digest outdated count method.
- Updates `digests/dependencies_test.go` adding test for `digestOutdatedCount()`
- fixes a check in outdated dependency to check top-level dep for outdated-ness before doing calculations on it
- Updates `scans/results.go`, adding `OutdatedMeta` struct to hold information for major, minor versions behind.
- Updates vendored code, ran dep ensure

[ION-499] updated outdated deps to track major minor version behind

---

digests/dependencies.go
digests/dependencies_test.go

- Update `digests/dependencies.go`, remove string comparison for outdated versions, compare on SemVer instead.
- updates `dependencies_test.go`
(for example: https://play.golang.org/p/NlF8WyplAyY versions like `5.14.x` and 5.9.x` would not count as "outdated" if the string compare was present).

[ION-568] remove outdated dep string compare

---

digests/dependencies_test.go

- Updates `digests/dependencies_test.go`, cleans up test output moves to Expect() block. Remove print statements.

cleanup dependency test output, move to expected block

---

digests/dependencies.go

These changes are required because the rule evaluation for "more than one major version behind" only applies to the outdated dependencies digest, but is attempted to be applied to the no versions specified digest.
Corrects this and adds a note for where changes will be made for future rules like "more than one minor version behind."

Make digests reflect more-than-one-major-version-behind rule.

---

digests/dependencies.go

Like https://github.com/ion-channel/ionic/pull/440 but for the next rule in the same vein.
I'd like to get the service PR merged before this one.

Make digests work for next major version behind rule.

---

digests/community.go
digests/community_test.go
digests/digests.go
scans/results.go

- updates `results.go`, `CommunityResults` struct updating to use committed_at time so it can be propagated through from scan data

[ION-575] update community results to include committed at time

---

digests/community.go
digests/community_test.go
digests/digests.go
scans/results.go

- Updates `digests/community.go` updating community digest, update to handle handle legacy scans, update to change digest to "days since last commit".
- update tests

[ION-575] update community results to include last updated time

---

reports/project.go
reports/project_test.go
rulesets.go
rulesets/applied_rulesets.go

Adds a method to retrieve less information about applied rulesets. The main GetAppliedRuleSets method can return tons of data that you don't necessarily need.

Add GetAppliedRuleSetsBrief

---

projects/projects.go

This was causing errors when attempting to add projects with upper-case in certain spots, like `HTTPS://github.com/...`

Convert project source to lowercase before validating

---

spdx/spdx.go
spdx/spdx_test.go

Wasn't stripping the '@branch-name' at the end of a git URL, which was causing analyses to fail.

[ION-845] Fix bug in project source after SPDX import

---

aliases/aliases.go
cyclonedx/cyclonedx.go
projects/projects.go
projects/projects_test.go
spdx/spdx.go

If an SBOM contains a component multiple times, only create one project for that component.
For example, if multiple dependencies all share a transitive dependency, we would not want to create multiple of the exact same project for that transitive dependency.
Also changes the Project Alias generation behavior for CycloneDX to match SPDX's behavior. SPDX generates an Alias using any available information (name, version, OR org), but CycloneDX was only generating an Alias if we had the name, version, AND org.

[ION-1081] Filter duplicate projects when parsing SBOM to projects

---

projects/sboms.go

[ION-1186] Allows us to differentiate between package, repo, and product search results.
[ION-1218] Facilitates backend work for ION-1218
[ION-1186]: https://ionchannel.atlassian.net/browse/ION-1186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ION-1218]: https://ionchannel.atlassian.net/browse/ION-1218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ION-1186] [ION-1218] Add additional fields to SBOMEntry

---

projects/sboms.go

With multiple SBOM files inside one Ion SBOM this field is no longer meaningful.

Remove sbom_type field as it's being deprecated.

---

organizations.go

One more function slipped through while #547 was sitting in the draft state

Revise pointer usage in GetOwnOrganizations

---

cyclonedx/cyclonedx.go
reports.go
reports/sbom.go

- Adds some additional options for exporting SBOMs
- Allows ingesting CycloneDX SBOMs that are missing the top-level component in the metadata (some tools generate SBOMs like this)

[ION-1292] [ION-1366] Additional SBOM export options, allow ingesting slightly invalid CycloneDX SBOMs

---

projects.go
projects/projects.go
projects_test.go

The getProjects endpoint no longer requires the Team ID to be passed in for every request.
Moves the filter argument to be the first one in the function call.

[ION-1292] Refactor getProjects

---

analyses.go
analyses_test.go
scanner.go

This parameter is no longer necessary to use the endpoint.

[ION-1292] Remove teamID parameter from GetLatestAnalysisSummaries

---

projects.go

Ruleset ID is no longer required when creating a project (uses the default ruleset if not provided)
Validation happens on the back-end.

[ION-1397] Simplify createProjects and updateProjects usage

---

projects/software_lists.go
reports/sbom.go

Adds enums for supported SBOM standards and encodings.
Renames Stats struct back to Metrics (accidentally pushed outdated code)

[DEV-341] Add supported SBOM standards and encodings, rename Stats

---

products/products.go

We're removing the following product metrics from use:
'average_high_severity'
'average_low_severity'
'average_medium_severity' 
It was determined that average_severity is sufficient on its own to achieve the goal of measuring average vulnerability severity of a product, and therefore these metrics aren't necessary.

[DEV-1603] remove 3 average severity metrics from product metric obj
